from .core import (
    word_count,
    top_n,
    normalize_whitespace,
    remove_punctuation,
    #is_palindrome,
    #unique_words,
    #reverse_words,
    #capitalize_sentences,
    #word_lengths,
    #strip_accents,
    #slugify,
    #count_vowels,
    #camel_to_snake,
    #truncate,
    #collapse_duplicates,
    #is_anagram,
    #compare_texts,
    #replace_numbers,
    #sentence_count,
    #average_word_length,
)

# Define __all__ for clarity
__all__ = [
    "word_count",
    "top_n",
    "normalize_whitespace",
    "remove_punctuation",
    "is_palindrome",
    "unique_words",
    "reverse_words",
    "capitalize_sentences",
    "word_lengths",
    "strip_accents",
    "slugify",
    "count_vowels",
    "camel_to_snake",
    "truncate",
    "collapse_duplicates",
    "is_anagram",
    "compare_texts",
    "replace_numbers",
    "sentence_count",
    "average_word_length",
]